.\" NAME
.TH _printf
.SH Function that produces output according to a format.
   
SYNOPSIS
.SH #include "main.h"
.SH int _printf(const char *format, ...)
    
DESCRIPTION
.SH The _printf() function produces output according to a format.
.SH _printf() write output to the stdout, the standard output stream.

		%c	-	Print a character
		%s	-	Print a string
		%%	-	Print a percentage
		%d	-	Print a decimal
		%i	-	Print an integer

EXAMPLES
.SH Some examples of common usage.
	_printf("Hello World");
	_printf("I'm", %d,"years old")

RETURN VALUE
.SH Return the numbers of character counted

DATE
.SH 27 November 2024

AUTHORS
.SH Antoine MUSCI	
.SH Kevin ROUGET		
.SH Alexandre MOUSSE	
